server:
  port: 8080
  servlet:
    context-path: /
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

  main:
    allow-bean-definition-overriding: true

  datasource:
    driver-class-name: org.postgresql.Driver
    username: egovboot
    password: egovboot
    url: jdbc:postgresql://localhost:5432/EgovBoot_4.1.2?connectionTimeZone=Asia/Seoul
logging:
  level:
    root: debug